### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by gab618** [gab618/ezrealblindado-api#1]
TODO

- [x] senha para criar links
- [x] rota api
  - [x] Contador de Maestria
  - [x] Tweetar quote (aguardando conta)
  - [x] Dar pontos
  - [x] Game
    - [x] migration: Game { key }; GameLog { user, points, date}
    - [x] model
    - [x] controller
      - [x] create: return new key
      - [x] delete: validate key, decrypt key, delete key from db, create log
